#!/usr/bin/env python3

import sys
import paramiko

host = sys.argv[1]
mountpoint = sys.argv[2]
path = sys.argv[3]

ssh = paramiko.SSHClient()
ssh.load_system_host_keys()
ssh.connect(host, username='root')


stdin, stdout, stderr = ssh.exec_command('btrfs subvolume list {}'.format(mountpoint))

for line in stdout.readlines():
    subvolume = line.split()
    print(subvolume[8])
