#!/bin/bash

# Based on:
# http://marc.merlins.org/perso/btrfs/post_2014-04-27_Btrfs-Multi-Device-Dmcrypt.html

die () {
    echo "$1"
    exit 1
}

print_help() {
    echo "usage: btrfs-crypt <BTRFS_LABEL>"
    echo
    echo "loads config from /etc/btrfs-crypt/<BTRFS_LABEL>.conf"
    echo "this file defines two variables. e.g."
    echo
    echo "    MOUNTPOINT=/tank"
    echo
    echo "    DRIVES=\""
    echo "    b10cd8cc-b721-483a-94f3-3d006036b991"
    echo "    7551ce14-0291-485f-b74b-d4007d3e0a64"
    echo "    \""
}

if [[ $# -ne 1 ]]; then
    print_help
    exit 1
fi

LABEL=$1

if [[ ! -f "/etc/btrfs-crypt/$LABEL.conf" ]]; then
    echo "error: $LABEL not defined."
    exit 1
fi

. /etc/btrfs-crypt/$LABEL.conf

read -s -p "LUKS key: " luks_key
echo

for d in $DRIVES
do
    dev=$(basename $(readlink /dev/disk/by-uuid/$d))
    echo "$luks_key" | cryptsetup luksOpen "/dev/$dev" "crypt_$dev" || die "$dev decryption failed"
    echo "$dev decrypted"
done

btrfs device scan
mkdir -p $MOUNTPOINT
mount -o defaults,noatime /dev/disk/by-label/$LABEL $MOUNTPOINT || die "Couldn't find btrfs $LABEL"
echo "btrfs $MOUNTPOINT mounted"
