#!/usr/bin/env python3

# Copyright 2012 Mike Sampson

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import glob
import mimetypes
import subprocess

def mplayer(filename):
    fd = open('/dev/null')
    subprocess.Popen(['mplayer', filename], stdin = fd, stdout = fd, stderr = fd)
    fd.close()

def select_media():
    def fn(filename):
        mt = mimetypes.guess_type(filename)[0]
        return mt != None and mt.startswith('video')

    files = list(filter(fn, glob.glob('*')))

    if not files:
        print('No media files found in current directory.')
        return

    files.sort()

    for i,f in enumerate(files):
        print('[%2d] - %s' % (i, f))

    selection = input('\nSelect file to play (0 to %d, q to quit): ' % (len(files) - 1))
    if selection == 'q':
        return

    try:
        selection = int(selection)
        mplayer(files[selection])
    except:
        print('Invalid selection.')

if len(sys.argv) == 1:
    select_media()
else:
    mplayer(sys.argv[1])
