#!/usr/bin/env python3

import sys

try:
    import ipaddress
except:
    print('Error: ipaddress module not found. This module is included in Python 3.3+')
    print('       or can be installed from pypi.')
    sys.exit(1)


def ptr(addr):
    "convert an IPv4 or IPv6 address into PTR format."
    return ipaddress.ip_address(addr).reverse_pointer

def main():
    if len(sys.argv) == 2:
        try:
            print(ptr(sys.argv[1]))
        except:
            print('Error: Invalid input.')
            sys.exit(1)
    else:
        print('Usage: ptr <IPv4Address|IPv6Address>')
        sys.exit(1)

if __name__ == '__main__':
    main()
